# Generated by Django 4.2.3 on 2024-01-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_control_user_record_reporting_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_record",
            name="quote_generator",
            field=models.BooleanField(default=False),
        ),
    ]
